import { environment } from '../../../enviroments/enviroment';

export const API = {
  login: `${environment.apiUrl}/login`,
  naturaleza: `${environment.apiUrl}/naturaleza`,
  unidadmedida: `${environment.apiUrl}/unidadmedida`,
  linea: `${environment.apiUrl}/linea`,
  color: `${environment.apiUrl}/color`,
  marca: `${environment.apiUrl}/color`,
  condicion: `${environment.apiUrl}/condicion`,
  concepto: `${environment.apiUrl}/concepto`,
  sublinea: `${environment.apiUrl}/sublinea`,
  almacen : `${environment.apiUrl}/almacenes`,
  transportista: `${environment.apiUrl}/transportista`,
  vendedor: `${environment.apiUrl}/vendedor`,
  series: `${environment.apiUrl}/series`,
  documentos: `${environment.apiUrl}/documentos`,
  tipocambio: `${environment.apiUrl}/tipocambio`,
  clientes: `${environment.apiUrl}/clientes`,
  empresatransporte: `${environment.apiUrl}/empresatransporte`,
  tipoDocumento: `${environment.apiUrl}/tipo_documento`,
  tipoPersona: `${environment.apiUrl}/tipo_persona`,
  moneda: `${environment.apiUrl}/moneda`,
  tipo_documentos: `${environment.apiUrl}/tipo_documento`,
  tipoFactura: `${environment.apiUrl}/tipo_factura`,
  tipoOperacion: `${environment.apiUrl}/tipo_operacion`,
  tipoAfectacion: `${environment.apiUrl}/tipo_afectacion`,
  tipoND: `${environment.apiUrl}/tipo_nd`,
  tipoNC: `${environment.apiUrl}/tipo_nc`,
  productos: `${environment.apiUrl}/productos`,
  productosconsulta: `${environment.apiUrl}/productos/consultastock`,
  proveedores: `${environment.apiUrl}/proveedor`,
  ubigeo: `${environment.apiUrl}/ubigeo`,
  ingresosSerie: `${environment.apiUrl}/ingresos/serie`,
  ingresos: `${environment.apiUrl}/ingresos`,
};
